.gitignore, blockchain/gen/messaging/ttypes.py, blockchain/network.py, blockchain/processing.py, blockchain/util/crypto.py, blockchain/util/thrift_conversions.py, scripts/valid_payload.json, thrift/messaging.thrift
`lower_phase_hash` is now included as a top level parameter in `sign_verification_record`. Also being appended to hashed_items separately from `verification_info`.
`phase_1` lower phase hash is being set to 0 since there's not a phase lower than `phase_1`.
`phase_3`  is keeping the list of `phase_2` `lower_phase_hashes` in addition to creating a separate `lower_phase_hash` from the hash of `lower_phase_hashes`,  which is included as a top level parameter.
--Took note to consider storing a structure of (`signatory`, `hash`) rather than `lower_phase_hashes` in `phase_3`.
Ran and tested the code after making the changes through `phase_4` without issues.
=> Issue 8/move lower phase hash

blockchain/network.py, blockchain/processing.py, blockchain/util/crypto.py
All thrift conversions are now being done in network.py. Ran and tested up to phase 4 without issues.
May have to relook at issue-37 (refactoring lower_phase_hash) due to code being moved around.
=> issue-34/isolate thrift dependencies

blockchain/processing.py
No changes to thrift file needed. Ran and tested without issues.
=> lower_phase_hashes in phase 3 is now a list of "signatory:hash" pairs.

sql/txpool.sql
There seems to be no public versions with non-pluralized table names, so may as well remove this legacy support now.
=> Remove uneeded legacy version support

README.md
Providing clarity in the public/private key generation process to create less friction on setup for developers stepping through the Readme file
=> Improved clarity on public/private key generation in Readme

.gitignore, README.md, blockchain/gen/messaging/BlockchainService.py, blockchain/gen/messaging/ttypes.py, blockchain/network.py, blockchain/processing.py, blockchain/transaction_svc.py, blockchain/util/crypto.py, blockchain/util/insert_db.py, blockchain/util/thrift_conversions.py, configs/blockchain.yml, thrift/messaging.thrift
issue #20 
`Phase_5_msg` in `messaging.thrift` is now a union that accepts either a `Transaction`, `VerificationRecord`, `hash` or a `miscellaneous string`.
`VerificationRecord` is a union that can either be a phase 1, 2, 3 or 4 `thrift` message type.
Implemented a public broadcast function in `network` that takes in a block, sets `VerificationRecord` and `phase_5_msg` and sends the block out to all known phase 5 nodes for `public transmission`.
Added public transmission on/off switches for all phases to the `blockchain.yml` network config. i.e if a config is set to `on` for phase 2, that block will be sent for `public transmission` by all phase 2 nodes it is sent to. If it's set to `off`, it is not sent for `public transmission`. Each phase checks for public transmission switches.
Added …
=> Issue 20/phase5 definition change

.gitignore, README.md, blockchain/processing.py, blockchain/query_svc.py, blockchain/transaction_svc.py
1. Set up .gitignore to ignore Emacs automatic backup files.
2. Document a warning that the signing key must be kept private, and that we
have set up .gitignore to prevent accidentally committing them to source
control.
3. Document requirement to create logs directory.
4. Add shebang lines to call the Python interpreter.
=> Setup and execution improvements.

.gitignore
This change adds 3 entries to the .gitignore file to ignore eclipse specific files.  Some people like to develop in eclipse.
=> Add eclipse specific project files to .gitignore

.gitignore, docs/smart-contracts.md
Initial user-facing smart contract documentation. This covers TSCs and includes some simple usage examples. Only TSCs are explained since they're business relevant and beginner friendly.
=> #99 initial TSC docs

docker/Processor_Dockerfile
Resolve issue #150 by using unbuffered python output in docker containers.
=> use unbuffered output from the processing node in docker

CHANGELOG.md, dragonchain/lib/dto/smart_contract_model.py
Disable schedule wasn't getting properly exported on contract build jobs. Now they are
Ran locally to test with removing both a cron schedule, and a seconds interval schedule, which worked correctly.
Fixes #213
=> Fix disable contract schedule update

dragonchain/webserver/lib/misc.py
#204 didn't properly fix the 404 for level 5 hits on the status endpoint when there is no default interchain set.
This should finish properly fixing that bug
=> fix 500 on status get for lvl5

CHANGELOG.md, dragonchain/lib/dto/eth.py
L5 ethereum chains could estimate 0 for a gas price, which would cause transactions to fail.
This PR puts in a minimum gas price of 0.1 gwei for safety against this.
=> set minimum gas price for ethereum

.vscode/settings.json, CHANGELOG.md, Dockerfile, README.md, cicd/Dockerfile.dependencies, cicd/Dockerfile.test, dragonchain/broadcast_processor/broadcast_functions_utest.py, dragonchain/broadcast_processor/broadcast_processor_utest.py, dragonchain/lib/database/redis_utest.py, mypy.ini, tools.sh
Closes #212
This PR updates dragonchain to use python3.8
Note that not all of our development tools (namely flake8) full support python3.8, so although we can use python3.8, we can't necessarily use all of the new syntax features (such as walrus operators) of python3.8 until those are also updated, or tests will fail.
Not a huge deal, and shouldn't block us from getting the other python3.8 benefits in the mean-time.
=> Move from python3.7 to python3.8

CHANGELOG.md, dragonchain/lib/matchmaking.py, dragonchain/transaction_processor/level_1_actions.py, requirements.txt
Fixes #242 
This fixes the infinite recursion when trying to register with dragon net.
With these changes, it will only retry registering up to 2 times total in worst case scenario before failing.
This PR also makes it so that an L1 chain transaction processor doesn't have to have an active dragon net registration to work properly, even when dragon net broadcasting is enabled
=> Fix dragonnet registration recursion and only warn if chain cannot register

CHANGELOG.md, dragonchain/lib/dto/bnb.py, dragonchain/lib/dto/bnb_utest.py, dragonchain/lib/dto/btc.py, dragonchain/lib/dto/btc_utest.py
Integration tests were failing because the endpoints for interchains were timing out
=> reduce interchain timeout

CHANGELOG.md, docs/deployment/deploying.md, dragonchain/lib/dao/block_dao.py, dragonchain/lib/database/redisearch.py, dragonchain/transaction_processor/level_5_actions.py, dragonchain/webserver/routes/blocks.py, dragonchain/webserver/start.py, helm/dragonchain-k8s/templates/configmap.yaml, helm/dragonchain-k8s/templates/deployment.yaml, helm/dragonchain-k8s/templates/security.yaml, helm/dragonchain-k8s/templates/service.yaml, helm/dragonchain-k8s/templates/volumes.yaml, helm/dragonchain-k8s/values.yaml, helm/opensource-config.yaml, requirements.txt, scripts/check_packages.py
This PR makes redisearch an optional component for L2+ nodes.
If redisearch is disabled, then all query endpoints are also disabled. Re-enabling redisearch after being disabled will automatically backfill all indexes, so no data is lost if redisearch is accidentally disabled/deleted on a node.
Note that _by default_ with this update, redisearch is disabled, thus existing nodes that update with this code will have their redisearch disable unless they set the proper helm value when updating.
=> Make redisearch optional on verification nodes

CHANGELOG.md, dragonchain/webserver/lib/misc.py, dragonchain/webserver/lib/misc_utest.py
Adds a new `indexingEnabled` response field to the get status endpoint which indicates if redisearch is on or off
=> Update status endpoint to indicate if indexing is on or off

CHANGELOG.md, dragonchain/lib/dao/api_key_dao.py, dragonchain/lib/dao/api_key_dao_utest.py, dragonchain/webserver/lib/api_keys.py, dragonchain/webserver/lib/api_keys_utest.py
Smart contract api keys were unable to have any permissions except the default permissions, so this update allows a smart contract api key to be updated (and listed/viewed).
Additionally this PR removes the concept of an api key starting with WEB_ from being reserved; This used to be an old concept for the managed dragonchain service, but has not been used for a while.
=> Allow updating smart contract api keys, and remove 'reserved' key concept from WEB_ keys

CHANGELOG.md, docs/deployment/raspberry_pi.md, docs/index.rst, dragonchain/job_processor/contract_job.py, dragonchain/job_processor/contract_job_utest.py, dragonchain/lib/dto/eth.py, dragonchain/lib/dto/eth_utest.py, dragonchain/webserver/lib/interchain.py, dragonchain/webserver/routes/interchain.py, requirements.txt
This PR deprecates support for the ethereum classic testnet (Morden), which is no longer used by the ethereum classic community.
It also adds docs about deploying dragonchain to a raspberry pi.
=> Deprecate morden and add raspi docs

CHANGELOG.md, dragonchain/lib/dto/schema.py
Some characters would not work as openfaas secret names, and others (such as uppercase letters) get converted.
This PR simply restricts the charset of smart contract secret names to be a simple set that should never cause a smart contract build to fail, or get unexpectedly converted
This charset is: a-z, 0-9, and the literal character `-`
=> Restrict smart contract secret name charset

CHANGELOG.md, Dockerfile, Dockerfile.arm64, cicd/Dockerfile.dependencies, cicd/Dockerfile.dependencies.arm64, dragonchain/broadcast_processor/broadcast_functions_utest.py, dragonchain/broadcast_processor/broadcast_processor_utest.py, dragonchain/lib/database/redis_utest.py, requirements.txt
Python 3.8.1 introduced a breaking change to how async tests are performed, which broke some of our tests when running on python 3.8.1
This PR fixes the tests to be compatible
=> fix tests (python 3.8.1)

CHANGELOG.md, dragonchain/job_processor/job_processor.py, dragonchain/job_processor/job_processor_utest.py, dragonchain/lib/database/redis.py, dragonchain/lib/database/redis_utest.py, tools.sh
Completes an old JIRA item to add recovery flow to job processor in case of unexpected crashes.
=> Add recovery queue and brpoplpush to job processor

dragonchain/lib/callback.py
For every transaction that gets processed, two logs are printed, making the transaction processor logs with big blocks pretty unusable. This PR simply removes those logs
=> remove tx processor callback checking logs

CHANGELOG.md, dragonchain/webserver/lib/dragonnet.py, requirements.txt
Fixes #298
Adds generic try/except so that a failure on any individual L1 block in an L5 does not affect the other blocks
Also adds a specific try/catch around fetching the claim check, so if the claim check doesn't exist for a block, it is specifically ignored
=> Fix l5 receipt processing bug

.github/CODEOWNERS, .vscode/settings.json, CHANGELOG.md, docs/usage/permissioning.md, dragonchain/lib/dto/api_key_model.py, dragonchain/lib/dto/bnb.py, dragonchain/lib/dto/bnb_utest.py, dragonchain/lib/dto/btc.py, dragonchain/lib/dto/btc_utest.py, dragonchain/lib/dto/eth.py, dragonchain/lib/dto/eth_utest.py, dragonchain/lib/dto/model.py, dragonchain/lib/dto/schema.py, dragonchain/webserver/lib/interchain.py, dragonchain/webserver/lib/interchain_utest.py, dragonchain/webserver/routes/interchain.py, requirements.txt
Adds endpoint for ability to publish (already signed) interchain transactions through dragonchain
=> add interchain transaction publish

CHANGELOG.md, dragonchain/transaction_processor/level_5_actions.py, dragonchain/transaction_processor/level_5_actions_utest.py, requirements.txt
If an l5 had a recovery backlog queue, it would not tolerate claim checks which have already been resolved by another l5, and will not process any of the backlog.
This PR fixes that by appropriately ignoring 404's from matchmaking.
=> fix l5 backlog queue

dragonchain/exceptions.py, dragonchain/webserver/helpers.py, dragonchain/webserver/lib/interchain.py
This PR attempts to provide a better error for the end user if an interchain transaction publish fails for any reason
=> provide better error when interchain publish fails

dragonchain/webserver/lib/transactions.py
The update to redisearch 1.6.7 changed an error string that we relied upon to determine if a transaction type exists when querying.
This PR fixes that
=> fix transaction query with bad type
