dragonchain/dragonchain

.gitignore
blockchain/util/crypto.py
scripts/valid_payload.json

Created a global list to check which items from transaction header not to include in verification and signing transactions. Tested an ran several posted transactions without issues.

issue-2/global-requirement-header

---

blockchain/db/postgres/network_db.py

Finally got the unregistered_nodes changed to check within 7 days.

Changed 5 minutes to 7 days in get_unregistered_nodes

---

blockchain/network.py
blockchain/processing.py
blockchain/query_svc.py

issues #42. Added constants in various files where appropriate. Ran and tested without issues.

Issue 42/Add-constants

---

.gitignore
blockchain/db/postgres/transaction_db.py
blockchain/query_svc.py

Issue #28 Added query services for all header fields. 
Can be queried by running query_svc.py and navigating to http://localhost:8080/transaction/?header_field=value also implemented is querying by timestamp. Note: All timestamps must be unix epoch timecode to work when querying. localhost:8080/transaction/?create_ts=1475155787.

Issue 28/query criteria

---

docker/Postgres_Dockerfile
docker/Processor_Dockerfile
docker/Query_Dockerfile
docker/Transaction_Dockerfile
docker/bootstrap.sh
docker/docker-compose.yml
docker/postgres-init.sh

run `docker-compose up` from the docker folder to spin up a fresh dragonchain test environment.

added docker compose support

---

setup.py

This change provides a friendlier error message for developers who
attempt to run the gen_thrift build command documented in README.md
without having the Thrift binary installed.
Before this patch, running "python setup.py gen_thrift" on a system
without Thrift installed results in this error:
> python setup.py gen_thrift
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'gen_thrift'
This makes it look like the developer ran the command incorrectly, even
though gen_thrift is the correct command.
After this patch, running "python setup.py gen_thrift" on a system
without Thrift installed results in this error:
> python setup.py gen_thrift
running gen_thrift …

gen_thrift friendlier error without Thrift binary.

---

blockchain/util/crypto.py

added crypto module docs

---

blockchain/db/postgres/sub_from_db.py
blockchain/db/postgres/sub_to_db.py

Added more documentation to sub_to and sub_from modules.
Let me know if you would like to see anything else included...
Thanks.

Subscription Database Documentation

---

blockchain/db/postgres/network_db.py
blockchain/db/postgres/sub_from_db.py
blockchain/db/postgres/sub_to_db.py
blockchain/db/postgres/sub_vr_transfers_db.py
blockchain/db/postgres/transaction_db.py
blockchain/db/postgres/verification_db.py
blockchain/db/postgres/vr_transfers_db.py

Fixing SI issue

---

blockchain/db/postgres/smart_contracts_db.py
blockchain/smart_contracts/smart_contracts.py
sql/smart_contracts.sql

121 - fixed over-deduping of vrs

---

blockchain/db/postgres/network_db.py

128 - fixed paramterization issue

---

blockchain/smart_contracts/smart_contracts.py

Allowing smart contracts to be base64 encoded to avoid escaping issues etc...

#130 base64 decode smart contracts

---

blockchain/transaction_svc.py
docs/transactions.md

Modified the transaction service so it gives better error messages, when being passed bad json. 
Added documentation for the json format for transactions.

Issue 140/transaction post better error handling

---

blockchain/query_svc.py
blockchain/transaction_svc.py

To the Query and the Transaction Service.
This enables the Chrome browser to submit payloads and to query payloads on the chain.

Added CORS (Cross-Origin Resource Sharing)

---

dragonchain/lib/dto/l2_block_model.py
dragonchain/lib/dto/transaction_model.py

Fix transaction version

---

CHANGELOG.md
dragonchain/lib/database/redis.py
dragonchain/lib/dto/eth.py
dragonchain/lib/dto/eth_utest.py

Fixes #183
Documentation fixed in SDKs by:
https://github.com/dragonchain/dragonchain-sdk-javascript/commit/f44c10deee15bffb4cd3ae06aa41e48c2d2bd82b
https://github.com/dragonchain/dragonchain-sdk-python/commit/e31a9569b8d0aa46731d6fdc9952af65bddfb2fd

fix etc interchain

---

CHANGELOG.md
dragonchain/job_processor/contract_job.py
dragonchain/job_processor/contract_job_utest.py
dragonchain/lib/dto/schema.py
dragonchain/lib/dto/smart_contract_model.py
dragonchain/scheduler/scheduler.py
dragonchain/scheduler/scheduler_utest.py

Adds support to disable the schedule for an existing smart contract when updating

add disable schedule support

---

CHANGELOG.md
CONTRIBUTING.md
README.md
SECURITY.md

add bounty links and docs

---

dragonchain/lib/database/redisearch.py

Redisearch changed their error strings which require this update

update redisearch error check

---

dragonchain/lib/faas.py
dragonchain/webserver/lib/smart_contracts.py
dragonchain/webserver/lib/smart_contracts_utest.py

Fix the 404 functionality of get logs

Fix 404 functionality on get logs.

---

CHANGELOG.md
dragonchain/job_processor/contract_job.py
dragonchain/job_processor/contract_job_utest.py
dragonchain/lib/dto/smart_contract_model.py

Fixes a bug while deleting smart contracts and updates fwatchdog

Smart Contract Bug Fix

---

CHANGELOG.md
dragonchain/lib/dao/block_dao.py

Fix cache bug

---

CHANGELOG.md
dragonchain/exceptions.py
dragonchain/lib/dao/interchain_dao.py
dragonchain/lib/dao/interchain_dao_utest.py
dragonchain/webserver/helpers.py
dragonchain/webserver/lib/interchain.py
dragonchain/webserver/lib/interchain_utest.py

make interchain create safe

---

CHANGELOG.md
dragonchain/lib/dto/btc.py
dragonchain/lib/dto/eth.py
dragonchain/lib/dto/model.py
dragonchain/lib/dto/transaction_model.py
dragonchain/lib/interfaces/storage.py
dragonchain/lib/matchmaking.py

Fixes miscellaneous bugs.
Fixes #179 
Fixes #203

Misc bug fixes

---

CHANGELOG.md
dragonchain/webserver/helpers.py
dragonchain/webserver/routes/__init__.py

fix 404 bug

---

CHANGELOG.md
docs/deployment/deploying.md
dragonchain/lib/queue.py

Fixes a bug where the repr of a bytes object was interpolated into the redis deadline key string

fix deadline bug

---

dragonchain/webserver/lib/interchain.py
dragonchain/webserver/lib/interchain_utest.py

#202 Introduced a bug which broke interchain update. This PR fixes that bug

fix intrechain update

---

CHANGELOG.md
dragonchain/job_processor/contract_job.py
dragonchain/job_processor/contract_job_utest.py
dragonchain/lib/database/redisearch.py
dragonchain/lib/dto/schema.py
helm/dragonchain-k8s/values.yaml
requirements.txt

Various changes as prep for release

Dependency Updates + Small Changes For Release

---

README.md
helm/dragonchain-k8s/Chart.yaml

Update Logo URL

---

dragonchain/lib/dto/bnb.py
dragonchain/transaction_processor/level_5_actions.py

use base64 despite docs asking for hex

---

CHANGELOG.md
dragonchain/lib/dto/schema.py
dragonchain/lib/faas.py
dragonchain/webserver/routes/smart_contracts.py
requirements.txt

Small fixes

---

dragonchain/lib/dto/bnb.py

`_publish_transaction` accidentally building txn twice; fixed, added error logging.

BNB bugfix.

---

CHANGELOG.md
Dockerfile
cicd/Dockerfile.dependencies
cicd/Dockerfile.test

Gunicorn 20.0.0 is failing to start due to this issue: https://github.com/benoitc/gunicorn/issues/2160
This PR is a temporary fix around this issue until gunicorn upstream is fixed and released.

Fix gunicorn

---

CHANGELOG.md
dragonchain/job_processor/contract_job.py
dragonchain/job_processor/templates/dockerfile.template
dragonchain/lib/dto/smart_contract_model.py
dragonchain/lib/interfaces/aws/ecr.py
dragonchain/lib/interfaces/aws/s3.py
dragonchain/lib/interfaces/docker_registry.py
dragonchain/lib/interfaces/local/disk.py
dragonchain/lib/interfaces/registry.py
dragonchain/lib/interfaces/storage.py
dragonchain/webserver/lib/smart_contracts.py
requirements.txt

This PR fixes a few bugs related to on-premises L1 operation.
These bug fixes should be considered effectively mandatory in order to run an L1 chain with smart contracts with the provided helm chart in this repo, and is ***highly*** recommended to upgrade if running on-prem regardless.
Fixes #247 for all new contracts. Old contracts in danger of this bug should update their contract after updating
Fixes #248 
Fixes #249
Fixes #250
Fixes #251
Fixes #253 
Fixes #254

On-prem L1 Bug fixes

---

CHANGELOG.md
README.md
helm/dragonchain-k8s/README.md
helm/dragonchain-k8s/values.yaml
requirements.txt

Add getting started links and update some dependencies

Add getting started links/update dependencies

---

CHANGELOG.md
dragonchain/exceptions.py
dragonchain/lib/broadcast.py
dragonchain/lib/matchmaking.py
dragonchain/transaction_processor/level_1_actions.py
dragonchain/transaction_processor/level_5_actions.py
dragonchain/transaction_processor/level_5_actions_utest.py

Fixes issue where L1 claims are not sent to matchmaking if matchmaking is down during the sending of receipts to lower level nodes.
See:  https://dragondev.atlassian.net/browse/DRGN-282

Fixes issue where claims aren't being sent to matchmaking.

---

CHANGELOG.md
dragonchain/broadcast_processor/broadcast_functions.py
dragonchain/broadcast_processor/broadcast_functions_utest.py
dragonchain/broadcast_processor/broadcast_processor.py
dragonchain/exceptions.py
dragonchain/lib/matchmaking.py

Support changes to matchmaking error code updates

---

CHANGELOG.md
dragonchain/lib/dto/schema.py
dragonchain/lib/queue.py
dragonchain/lib/queue_utest.py
dragonchain/webserver/lib/transactions.py
dragonchain/webserver/lib/transactions_utest.py

#263 changed the behavior of bulk endpoints. This reverts that change while keeping the bulk speedups.

fix bulk endpoint behavior

---

.travis.yml
CHANGELOG.md
cicd/CICD.cft.yml
cicd/Dockerfile.dependencies.arm64
cicd/Dockerfile.test.arm64
cicd/buildspec.deploy.yml
dev_requirements.txt
dragonchain/lib/types.py
requirements.txt
scripts/build_dependency_docker.sh
tools.sh

This PR adds docker building/checking for arm64 to the ci/cd

Add Arm64 builds

---

cicd/buildspec.deploy.yml

Fix the broken deployment buildspec

fix buildspec

---

CHANGELOG.md
dragonchain/broadcast_processor/broadcast_processor.py
dragonchain/broadcast_processor/broadcast_processor_utest.py
dragonchain/lib/dto/bnb.py
dragonchain/lib/dto/btc.py
dragonchain/lib/dto/eth.py
dragonchain/lib/queue.py

implementing deadline for L5s

---

cicd/buildspec.deploy.yml

fix docker manifest push

---

CHANGELOG.md
Dockerfile.arm64
Dockerfile.armv7
cicd/CICD.cft.yml
cicd/Dockerfile.dependencies
cicd/Dockerfile.dependencies.armv7
cicd/Dockerfile.test
cicd/Dockerfile.test.armv7
cicd/buildspec.deploy.yml
scripts/build_dependency_docker.sh

Add armv7 building for docker containers in the cicd

Armv7 builds

---

CHANGELOG.md
docs/deployment/requirements.md
helm/dragonchain-k8s/values.yaml
helm/opensource-config.yaml
requirements.txt

Tweaks helmchart resource usages to run better on lower power devices

tweak resource usages

---

CHANGELOG.md
Dockerfile
Dockerfile.arm64
cicd/Dockerfile.dependencies
cicd/Dockerfile.dependencies.arm64
cicd/Dockerfile.test
cicd/Dockerfile.test.arm64
dragonchain/broadcast_processor/broadcast_processor.py
dragonchain/broadcast_processor/broadcast_processor_utest.py
tools.sh

Bug fix for broadcast processor

broadcast processor fix

---

Dockerfile
Dockerfile.arm64
cicd/Dockerfile.dependencies
cicd/Dockerfile.dependencies.arm64
cicd/Dockerfile.test
cicd/Dockerfile.test.arm64

whoops, fixes breaking arm dockerfiles from #285

fix dockerfiles

---

dragonchain/broadcast_processor/broadcast_processor.py

fix take 3

---

CHANGELOG.md
dragonchain/broadcast_processor/broadcast_processor.py
dragonchain/broadcast_processor/broadcast_processor_utest.py
dragonchain/lib/dao/api_key_dao.py
dragonchain/lib/dto/api_key_model.py

Adds Missing Content-Type header to outbound verification notification requests.
- [] documentation is changed or added

adds header to verification notification

---

CHANGELOG.md
helm/dragonchain-k8s/templates/configmap.yaml

Fix Double Quoted JSON in helm template for VERIFICATION_NOTIFICATION

(configmap.yaml) Removes duplicate quotes

---

dragonchain/job_processor/job_processor.py
dragonchain/job_processor/job_processor_utest.py
dragonchain/lib/database/redis.py

Fix a smart contract creation bug (unreleased)

Fix contract bug

---

CHANGELOG.md
dragonchain/webserver/lib/verifications.py

bug fix for querying redisearch with a UUID chain ID instead of public key

Querying interchain broadcast bug fix with UUID chain ID

---

.vscode/settings.json
docs/deployment/deploying.md
docs/meta/community.md
dragonchain/lib/callback.py
tools.sh

Community wip 2022
